---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mytester.kubeta.github.io
  resources:
  - testers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mytester.kubeta.github.io
  resources:
  - testers/finalizers
  verbs:
  - update
- apiGroups:
  - mytester.kubeta.github.io
  resources:
  - testers/status
  verbs:
  - get
  - patch
  - update
