# permissions for end users to edit testers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tester-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8statester
    app.kubernetes.io/part-of: k8statester
    app.kubernetes.io/managed-by: kustomize
  name: tester-editor-role
rules:
- apiGroups:
  - mytester.kubeta.github.io
  resources:
  - testers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mytester.kubeta.github.io
  resources:
  - testers/status
  verbs:
  - get
